import { insertTrainingData } from '../../../lib/db';

export async function POST(request) {
  try {
    const sampleData = [
      {
        student_id: "S001",
        age: 20,
        gender: "Male",
        academic_program: "IT",
        year_level: "3rd year",
        GPA: 3.5,
        time_spent_on_videos: 10,
        time_spent_on_text_materials: 5,
        time_spent_on_interactive_activities: 8,
        forum_participation_count: 12,
        group_activity_participation: 7,
        individual_activity_preference: 3,
        note_taking_style: "typed",
        preference_for_visual_materials: true,
        preference_for_textual_materials: false,
        quiz_attempts: 5,
        time_to_complete_assignments: 2,
        learning_path_navigation: "linear",
        problem_solving_preference: "step-by-step",
        response_speed_in_quizzes: "fast",
        accuracy_in_detail_oriented_questions: 90,
        accuracy_in_conceptual_questions: 85,
        preference_for_examples: true,
        self_reflection_activity: true,
        clickstream_sequence: ["video1", "quiz1", "text1"],
        video_pause_and_replay_count: 15,
        quiz_review_frequency: 3,
        skipped_content_ratio: 0.1,
        login_frequency_per_week: 5,
        average_study_session_length: 60,
        active_vs_reflective: "active",
        sensing_vs_intuitive: "sensing",
        visual_vs_verbal: "visual",
        sequential_vs_global: "sequential",
      },
      {
        student_id: "S002",
        age: 21,
        gender: "Female",
        academic_program: "Engineering",
        year_level: "4th year",
        GPA: 3.8,
        time_spent_on_videos: 7,
        time_spent_on_text_materials: 12,
        time_spent_on_interactive_activities: 6,
        forum_participation_count: 8,
        group_activity_participation: 10,
        individual_activity_preference: 8,
        note_taking_style: "handwritten",
        preference_for_visual_materials: false,
        preference_for_textual_materials: true,
        quiz_attempts: 3,
        time_to_complete_assignments: 4,
        learning_path_navigation: "jumping around modules",
        problem_solving_preference: "holistic solution approach",
        response_speed_in_quizzes: "slow",
        accuracy_in_detail_oriented_questions: 80,
        accuracy_in_conceptual_questions: 95,
        preference_for_examples: false,
        self_reflection_activity: false,
        clickstream_sequence: ["text2", "forum1", "video2"],
        video_pause_and_replay_count: 5,
        quiz_review_frequency: 1,
        skipped_content_ratio: 0.2,
        login_frequency_per_week: 3,
        average_study_session_length: 90,
        active_vs_reflective: "reflective",
        sensing_vs_intuitive: "intuitive",
        visual_vs_verbal: "verbal",
        sequential_vs_global: "global",
      },
      {
        student_id: "S003",
        age: 19,
        gender: "Male",
        academic_program: "Business",
        year_level: "2nd year",
        GPA: 3.2,
        time_spent_on_videos: 12,
        time_spent_on_text_materials: 3,
        time_spent_on_interactive_activities: 10,
        forum_participation_count: 15,
        group_activity_participation: 5,
        individual_activity_preference: 6,
        note_taking_style: "none",
        preference_for_visual_materials: true,
        preference_for_textual_materials: false,
        quiz_attempts: 7,
        time_to_complete_assignments: 3,
        learning_path_navigation: "linear",
        problem_solving_preference: "step-by-step",
        response_speed_in_quizzes: "fast",
        accuracy_in_detail_oriented_questions: 88,
        accuracy_in_conceptual_questions: 80,
        preference_for_examples: true,
        self_reflection_activity: true,
        clickstream_sequence: ["video3", "interactive1", "quiz3"],
        video_pause_and_replay_count: 20,
        quiz_review_frequency: 4,
        skipped_content_ratio: 0.05,
        login_frequency_per_week: 6,
        average_study_session_length: 45,
        active_vs_reflective: "active",
        sensing_vs_intuitive: "sensing",
        visual_vs_verbal: "visual",
        sequential_vs_global: "sequential",
      },
      {
        student_id: "S004",
        age: 22,
        gender: "Female",
        academic_program: "IT",
        year_level: "4th year",
        GPA: 3.9,
        time_spent_on_videos: 8,
        time_spent_on_text_materials: 7,
        time_spent_on_interactive_activities: 9,
        forum_participation_count: 10,
        group_activity_participation: 12,
        individual_activity_preference: 7,
        note_taking_style: "typed",
        preference_for_visual_materials: true,
        preference_for_textual_materials: true,
        quiz_attempts: 6,
        time_to_complete_assignments: 2,
        learning_path_navigation: "linear",
        problem_solving_preference: "holistic solution approach",
        response_speed_in_quizzes: "fast",
        accuracy_in_detail_oriented_questions: 92,
        accuracy_in_conceptual_questions: 90,
        preference_for_examples: true,
        self_reflection_activity: false,
        clickstream_sequence: ["quiz4", "video4", "text3"],
        video_pause_and_replay_count: 10,
        quiz_review_frequency: 2,
        skipped_content_ratio: 0.15,
        login_frequency_per_week: 4,
        average_study_session_length: 75,
        active_vs_reflective: "active",
        sensing_vs_intuitive: "intuitive",
        visual_vs_verbal: "visual",
        sequential_vs_global: "global",
      },
      {
        student_id: "S005",
        age: 20,
        gender: "Male",
        academic_program: "Engineering",
        year_level: "3rd year",
        GPA: 3.6,
        time_spent_on_videos: 6,
        time_spent_on_text_materials: 9,
        time_spent_on_interactive_activities: 7,
        forum_participation_count: 9,
        group_activity_participation: 8,
        individual_activity_preference: 5,
        note_taking_style: "handwritten",
        preference_for_visual_materials: false,
        preference_for_textual_materials: true,
        quiz_attempts: 4,
        time_to_complete_assignments: 3,
        learning_path_navigation: "jumping around modules",
        problem_solving_preference: "step-by-step",
        response_speed_in_quizzes: "slow",
        accuracy_in_detail_oriented_questions: 85,
        accuracy_in_conceptual_questions: 88,
        preference_for_examples: false,
        self_reflection_activity: true,
        clickstream_sequence: ["text4", "quiz5", "interactive2"],
        video_pause_and_replay_count: 8,
        quiz_review_frequency: 2,
        skipped_content_ratio: 0.1,
        login_frequency_per_week: 5,
        average_study_session_length: 50,
        active_vs_reflective: "reflective",
        sensing_vs_intuitive: "sensing",
        visual_vs_verbal: "verbal",
        sequential_vs_global: "sequential",
      },
    ];

    const result = await insertTrainingData(sampleData);
    return new Response(JSON.stringify({ message: "Data populated successfully", insertedCount: result.insertedCount }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    });
  } catch (error) {
    console.error("Error populating data:", error);
    return new Response(JSON.stringify({ message: "Failed to populate data", error: error.message }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' },
    });
  }
}